name: Docker build and publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Enable QEMU for multi-arch builds
      run: docker run --rm --privileged tonistiigi/binfmt --install all

    - name: Create and bootstrap Buildx builder
      run: |
        docker buildx create --name ci-builder --use
        docker buildx inspect --bootstrap

    - name: Log in to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

    - name: Build and push image (main)
      if: github.event_name == 'push'
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --file ./Dockerfile \
          --push \
          --tag ghcr.io/${{ github.repository_owner }}/zapi2mqtt:latest \
          .

    - name: Build image only (PR)
      if: github.event_name == 'pull_request'
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --file ./Dockerfile \
          --load \
          --tag zapi2mqtt:pr-${{ github.sha }} \
          .
